services:
    webapp:
      build: .
      container_name: react-app
      ports:
       - "5173:5173"
      
    nginx:
      image: nginx:1-alpine
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8088:80"
      
      